bind '"\er": redraw-current-line'
bind '"\C-g\C-f": "$(fzf-gf)\e\C-e\er"'
bind '"\C-g\C-b": "$(fzf-gb)\e\C-e\er"'
bind '"\C-g\C-t": "$(fzf-gt)\e\C-e\er"'
bind '"\C-g\C-h": "$(fzf-gh)\e\C-e\er"'
bind '"\C-g\C-r": "$(fzf-gr)\e\C-e\er"'
